# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Include:
    - '*.gemspec'
    - 'Gemfile'
    - 'lib/**/*.rb'
    - 'Rakefile'
    - 'spec/**/*.rb'
  Exclude:
    - "**/vendor/**/*"
