# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  ExtraDetails: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Include:
    - '*.gemspec'
    - 'Gemfile'
    - 'lib/**/*.rb'
    - 'Rakefile'
    - 'spec/**/*.rb'
  Exclude:
    - "**/vendor/**/*"

Style/BlockDelimiters:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

LineLength:
  Enabled: false

ClassLength:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

HashSyntax:
   EnforcedStyle: ruby19

Style/SignalException:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ExtraSpacing:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/SingleLineBlockParams:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# alias / alias_method are both fine
Style/Alias:
  Enabled: false

# nice for .with{} mock stubs
Style/Semicolon:
  Enabled: false

# for simple cases more readable
Style/GuardClause:
  Enabled: false

# sometimes the most readable way of doing things
Style/ClassVars:
  Enabled: false

# for single `/` more readable
Style/RegexpLiteral:
  Enabled: false

# %w[] shows that it will return an array
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Lint/AssignmentInCondition:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

# Looks correct / intuitive
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# We use it a few times in tests and nobody does random nested method definitions
Lint/NestedMethodDefinition:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Lint/NonLocalExitFromIterator:
  Enabled: false

# Often makes logical sense to not combine if with elsif
Style/IfInsideElse:
  Enabled: false

# nil is often a perfectly fine exception result
Lint/SuppressedException:
  Enabled: false
